from pydantic import BaseModel
from typing import List

class RecipeIngredient(BaseModel):
    """
    Schema representing a single ingredient in the compost recipe.
    """
    name: str
    weight_kg: float
    moisture_content: float  # Percentage (0-100)
    nitrogen_content: float  # Percentage of dry matter (0-100)
    carbon_content: float    # Percentage of dry matter (0-100)

class ExpertSuggestion(BaseModel):
    """
    Schema for a single recommendation generated by the rule-based expert system.
    """
    issue: str
    recommendation: str
    severity: str  # e.g., "high", "medium", "low"

class RecipeEvaluation(BaseModel):
    """
    Schema for the final evaluation report returned to the user.
    """
    total_weight_kg: float
    calculated_cn_ratio: float
    calculated_moisture_percent: float
    suggestions: List[ExpertSuggestion]
    is_optimal: bool

class CompostExpertSystem:
    """
    Rule-Based Expert System that evaluates a compost mix recipe.
    It calculates the overall moisture and Carbon-to-Nitrogen (C/N) ratio,
    and returns recommendations to help the user achieve optimal composting conditions.
    """
    def __init__(self):
        # optimal ranges (literature ideal)
        self.min_cn_ratio = 25.0
        self.max_cn_ratio = 30.0
        self.min_moisture = 40.0
        self.max_moisture = 50.0

    def evaluate_recipe(self, ingredients: List[RecipeIngredient]) -> RecipeEvaluation:
        """
        Evaluates a list of ingredients and applies rules to generate suggestions.
        """
        if not ingredients:
            return RecipeEvaluation(
                total_weight_kg=0.0,
                calculated_cn_ratio=0.0,
                calculated_moisture_percent=0.0,
                suggestions=[ExpertSuggestion(
                    issue="Empty Recipe", 
                    recommendation="Please add ingredients to your compost mix to receive an evaluation.", 
                    severity="high"
                )],
                is_optimal=False
            )

        total_weight = 0.0
        total_water_weight = 0.0
        total_carbon_weight = 0.0
        total_nitrogen_weight = 0.0

        # calculate total weights for water, carbon, and nitrogen
        for item in ingredients:
            weight = item.weight_kg
            total_weight += weight
            
            # water weight is straight from moisture percentage
            water_weight = weight * (item.moisture_content / 100.0)
            total_water_weight += water_weight
            
            # dry weight is whatever remains after removing water
            dry_weight = weight - water_weight
            
            # carbon and Nitrogen amounts are based on the dry matter (dry weight)
            carbon_weight = dry_weight * (item.carbon_content / 100.0)
            nitrogen_weight = dry_weight * (item.nitrogen_content / 100.0)
            
            total_carbon_weight += carbon_weight
            total_nitrogen_weight += nitrogen_weight

        # calculate final metrics for the whole system
        system_moisture = (total_water_weight / total_weight) * 100.0 if total_weight > 0 else 0.0
        cn_ratio = (total_carbon_weight / total_nitrogen_weight) if total_nitrogen_weight > 0 else 0.0

        # rule-based logic engine: generating suggestions based on defined optimal ranges
        suggestions = []
        
        # 1. evaluate C/N Ratio
        if cn_ratio < self.min_cn_ratio:
            suggestions.append(ExpertSuggestion(
                issue=f"C/N Ratio is too low ({cn_ratio:.1f}:1)",
                recommendation="Your mix has too much nitrogen. Add more 'browns' (carbon-rich materials like corn stalks, corn cobs or cocoa shells) to increase the ratio.",
                severity="high"
            ))
        elif cn_ratio > self.max_cn_ratio:
            suggestions.append(ExpertSuggestion(
                issue=f"C/N Ratio is too high ({cn_ratio:.1f}:1)",
                recommendation="Your mix has too much carbon. Add more 'greens' (nitrogen-rich materials like grass clippings, fresh vegetable scraps, or coffee grounds) to lower the ratio.",
                severity="high"
            ))

        # 2. evaluate Moisture Level
        if system_moisture < self.min_moisture:
            suggestions.append(ExpertSuggestion(
                issue=f"Moisture is too low ({system_moisture:.1f}%)",
                recommendation="Your mix is too dry, which stops the composting process. Mix in more wet ingredients (greens), or you will need to add water progressively during the composting process.",
                severity="medium"
            ))
        elif system_moisture > self.max_moisture:
            suggestions.append(ExpertSuggestion(
                issue=f"Moisture is too high ({system_moisture:.1f}%)",
                recommendation="Your mix is too wet, which can cause foul odors. Mix in dry, bulky 'browns' (like cocoa shells, olive husks or corn stalks) to absorb excess moisture and improve aeration.",
                severity="medium"
            ))

        # check if recipe is optimal (no suggestions means it's within all optimal ranges)
        is_optimal = len(suggestions) == 0

        if is_optimal:
            suggestions.append(ExpertSuggestion(
                issue="Optimal Recipe",
                recommendation="Your compost mix looks great! Both the C/N ratio and moisture levels are perfectly balanced to start the composting process.",
                severity="low"
            ))

        return RecipeEvaluation(
            total_weight_kg=total_weight,
            calculated_cn_ratio=cn_ratio,
            calculated_moisture_percent=system_moisture,
            suggestions=suggestions,
            is_optimal=is_optimal
        )

# simple test case to demonstrate functionality
if __name__ == "__main__":
    expert_system = CompostExpertSystem()

    # FIRST EVALUATION: Only Apple processing sludge (high moisture, low C/N)
    test_recipe1 = [
        RecipeIngredient(
            name="Apple processing sludge", 
            weight_kg=10.00, 
            moisture_content=59.00, 
            nitrogen_content=1.15, 
            carbon_content=8.04
        )
    ]
    
    evaluation1 = expert_system.evaluate_recipe(test_recipe1)
    print("\n1 - First Compost Recipe Evaluation:")
    print(f"Total Weight: {evaluation1.total_weight_kg:.2f} kg")
    print(f"Calculated C/N: {evaluation1.calculated_cn_ratio:.2f}")
    print(f"Calculated Moisture: {evaluation1.calculated_moisture_percent:.2f}%\n")
    
    for s in evaluation1.suggestions:
        print(f"[{s.severity.upper()}] {s.issue}: {s.recommendation}")

    # SECOND EVALUATION: Adding Corn stalks (low moisture, high C/N) to balance the recipe
    test_recipe2 = [
        RecipeIngredient(
            name="Apple processing sludge", 
            weight_kg=10.00, 
            moisture_content=59.00, 
            nitrogen_content=1.15, 
            carbon_content=8.04
        ),
        RecipeIngredient(
            name="Corn stalks", 
            weight_kg=4.00, 
            moisture_content=12.00, 
            nitrogen_content=0.62, 
            carbon_content=40.66 
        )
    ]
    
    evaluation2 = expert_system.evaluate_recipe(test_recipe2)
    print("\n2 - Second Compost Recipe Evaluation:")
    print(f"Total Weight: {evaluation2.total_weight_kg:.2f} kg")
    print(f"Calculated C/N: {evaluation2.calculated_cn_ratio:.2f}")
    print(f"Calculated Moisture: {evaluation2.calculated_moisture_percent:.2f}%\n")
    
    for s in evaluation2.suggestions:
        print(f"[{s.severity.upper()}] {s.issue}: {s.recommendation}")